# Use the official Nginx image as a base
FROM nginx:alpine

# Copy custom configuration file if needed
# COPY nginx.conf /etc/nginx/nginx.conf

# Copy static website files if needed
COPY Blog/html /usr/share/nginx/html

EXPOSE 80